/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteUeberUnsRouteImport } from './routes/_site.ueber-uns'
import { Route as SitePreiseRouteImport } from './routes/_site.preise'
import { Route as SiteKundenRouteImport } from './routes/_site.kunden'
import { Route as SiteKontaktRouteImport } from './routes/_site.kontakt'
import { Route as SiteImpressumRouteImport } from './routes/_site.impressum'
import { Route as SiteFunktionenRouteImport } from './routes/_site.funktionen'
import { Route as SiteDatenschutzRouteImport } from './routes/_site.datenschutz'
import { Route as SiteBlogIndexRouteImport } from './routes/_site.blog.index'
import { Route as SiteBlogSlugRouteImport } from './routes/_site.blog.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteUeberUnsRoute = SiteUeberUnsRouteImport.update({
  id: '/ueber-uns',
  path: '/ueber-uns',
  getParentRoute: () => SiteRoute,
} as any)
const SitePreiseRoute = SitePreiseRouteImport.update({
  id: '/preise',
  path: '/preise',
  getParentRoute: () => SiteRoute,
} as any)
const SiteKundenRoute = SiteKundenRouteImport.update({
  id: '/kunden',
  path: '/kunden',
  getParentRoute: () => SiteRoute,
} as any)
const SiteKontaktRoute = SiteKontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => SiteRoute,
} as any)
const SiteImpressumRoute = SiteImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => SiteRoute,
} as any)
const SiteFunktionenRoute = SiteFunktionenRouteImport.update({
  id: '/funktionen',
  path: '/funktionen',
  getParentRoute: () => SiteRoute,
} as any)
const SiteDatenschutzRoute = SiteDatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBlogIndexRoute = SiteBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBlogSlugRoute = SiteBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/datenschutz': typeof SiteDatenschutzRoute
  '/funktionen': typeof SiteFunktionenRoute
  '/impressum': typeof SiteImpressumRoute
  '/kontakt': typeof SiteKontaktRoute
  '/kunden': typeof SiteKundenRoute
  '/preise': typeof SitePreiseRoute
  '/ueber-uns': typeof SiteUeberUnsRoute
  '/blog/$slug': typeof SiteBlogSlugRoute
  '/blog/': typeof SiteBlogIndexRoute
}
export interface FileRoutesByTo {
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/datenschutz': typeof SiteDatenschutzRoute
  '/funktionen': typeof SiteFunktionenRoute
  '/impressum': typeof SiteImpressumRoute
  '/kontakt': typeof SiteKontaktRoute
  '/kunden': typeof SiteKundenRoute
  '/preise': typeof SitePreiseRoute
  '/ueber-uns': typeof SiteUeberUnsRoute
  '/': typeof SiteIndexRoute
  '/blog/$slug': typeof SiteBlogSlugRoute
  '/blog': typeof SiteBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_site/datenschutz': typeof SiteDatenschutzRoute
  '/_site/funktionen': typeof SiteFunktionenRoute
  '/_site/impressum': typeof SiteImpressumRoute
  '/_site/kontakt': typeof SiteKontaktRoute
  '/_site/kunden': typeof SiteKundenRoute
  '/_site/preise': typeof SitePreiseRoute
  '/_site/ueber-uns': typeof SiteUeberUnsRoute
  '/_site/': typeof SiteIndexRoute
  '/_site/blog/$slug': typeof SiteBlogSlugRoute
  '/_site/blog/': typeof SiteBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/datenschutz'
    | '/funktionen'
    | '/impressum'
    | '/kontakt'
    | '/kunden'
    | '/preise'
    | '/ueber-uns'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sitemap.xml'
    | '/datenschutz'
    | '/funktionen'
    | '/impressum'
    | '/kontakt'
    | '/kunden'
    | '/preise'
    | '/ueber-uns'
    | '/'
    | '/blog/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/_site'
    | '/sitemap.xml'
    | '/_site/datenschutz'
    | '/_site/funktionen'
    | '/_site/impressum'
    | '/_site/kontakt'
    | '/_site/kunden'
    | '/_site/preise'
    | '/_site/ueber-uns'
    | '/_site/'
    | '/_site/blog/$slug'
    | '/_site/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/ueber-uns': {
      id: '/_site/ueber-uns'
      path: '/ueber-uns'
      fullPath: '/ueber-uns'
      preLoaderRoute: typeof SiteUeberUnsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/preise': {
      id: '/_site/preise'
      path: '/preise'
      fullPath: '/preise'
      preLoaderRoute: typeof SitePreiseRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/kunden': {
      id: '/_site/kunden'
      path: '/kunden'
      fullPath: '/kunden'
      preLoaderRoute: typeof SiteKundenRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/kontakt': {
      id: '/_site/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof SiteKontaktRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/impressum': {
      id: '/_site/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof SiteImpressumRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/funktionen': {
      id: '/_site/funktionen'
      path: '/funktionen'
      fullPath: '/funktionen'
      preLoaderRoute: typeof SiteFunktionenRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/datenschutz': {
      id: '/_site/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof SiteDatenschutzRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/blog/': {
      id: '/_site/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof SiteBlogIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/blog/$slug': {
      id: '/_site/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof SiteBlogSlugRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteDatenschutzRoute: typeof SiteDatenschutzRoute
  SiteFunktionenRoute: typeof SiteFunktionenRoute
  SiteImpressumRoute: typeof SiteImpressumRoute
  SiteKontaktRoute: typeof SiteKontaktRoute
  SiteKundenRoute: typeof SiteKundenRoute
  SitePreiseRoute: typeof SitePreiseRoute
  SiteUeberUnsRoute: typeof SiteUeberUnsRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteBlogSlugRoute: typeof SiteBlogSlugRoute
  SiteBlogIndexRoute: typeof SiteBlogIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteDatenschutzRoute: SiteDatenschutzRoute,
  SiteFunktionenRoute: SiteFunktionenRoute,
  SiteImpressumRoute: SiteImpressumRoute,
  SiteKontaktRoute: SiteKontaktRoute,
  SiteKundenRoute: SiteKundenRoute,
  SitePreiseRoute: SitePreiseRoute,
  SiteUeberUnsRoute: SiteUeberUnsRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteBlogSlugRoute: SiteBlogSlugRoute,
  SiteBlogIndexRoute: SiteBlogIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
